picoscope_resolutionBits: 16
picoscope_rangemV: 10
picoscope_blocks: 1
picoscope_blocksMax: 100
picoscope_timebase: 9
#Currently default sampling interval is hard coded to 144 nS
picoscope_externalTrigger: True
picoscope_triggermV: 5000
picoscope_triggermVMax: 10000
picoscope_preSamples: 0
picoscope_postSamples: 2500
picoscope_samplesMax: 1000000000
picoscope_delay: 104500
picoscope_delayMax: 100000000
picoscope_setSigGen: False
picoscope_baseTimePerWaveform: .00003
picoscope_baseTimePerPoint: .063
picoscope_baseDataPerScan: 264000
picoscope_baseDataPerPoint: 14000
picoscope_dataPerSample: 2
siglent_frequencyHz: '1600000'
siglent_frequencyHzMax: '10000000'
siglent_amplitudeV: '.8'
siglent_amplitudeVMax: '10'
siglent_burstPeriodS: '.01'
siglent_burstPeriodSMax: '1'
siglent_cycles: '50'
siglent_cyclesMax: '100'
siglent_C1output: 'OFF'
siglent_C2output: 'OFF'
galil_mmConversion: 1119
galil_xLimit: 10000000
galil_yLimit: 10000000
galil_zLimit: 10000000
galil_step: 1
galil_maxSamples: 1000

end_scan_on_errors: False
#nanoseconds
plot_xMin: 0
plot_xMax: 10000
#millivolts
plot_yMin: -10000
plot_yMax: 10000
plot_xPadding: .01
plot_yPadding: .1
