picoscope_resolutionBits: 16
picoscope_rangemV: 10000
picoscope_blocks: 10
picoscope_blocksMax: 100
picoscope_timebase: 2
picoscope_externalTrigger: True
picoscope_triggermV: 5000
picoscope_triggermVMax: 10000
picoscope_preSamples: 0
picoscope_postSamples: 2500
picoscope_samplesMax: 100000
picoscope_delay: 0
picoscope_delayMax: 1000
picoscope_setSigGen: False
siglent_frequencyHz: '1000000'
siglent_frequencyHzMax: '10000000'
siglent_amplitudeV: '10'
siglent_amplitudeVMax: '10'
siglent_burstPeriodS: '.0001'
siglent_burstPeriodSMax: '1'
siglent_cycles: '5'
siglent_cyclesMax: '100'
siglent_output: 'ON'
siglent_mmConversion: 1
galil_xLimit: 10000000
galil_yLimit: 10000000
galil_zLimit: 10000000
galil_step: 1
galil_maxSamples: 1000

end_scan_on_errors: False
#nanoseconds
plot_xMin: 0
plot_xMax: 10000
#millivolts
plot_yMin: -10000
plot_yMax: 10000
plot_xPadding: .01
plot_yPadding: .1
